# Generated by Django 5.1.7 on 2025-03-13 21:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produktimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='content_main.product'),
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('content', models.CharField(max_length=150)),
                ('text', models.CharField(max_length=300)),
                ('image', models.FileField(blank=True, null=True, upload_to='promotion/image/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png'])])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content_main.product')),
            ],
        ),
    ]
