# Generated by Django 5.1.7 on 2025-03-18 05:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_main', '0002_alter_produktimage_product_promotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_special',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='promotion/image/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg'])]),
        ),
    ]
