# Generated by Django 5.1.7 on 2025-03-19 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_main', '0005_filter_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='slug',
            field=models.SlugField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
